from __future__ import annotations

import hashlib
import json
import os
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.channel_mapping import ChannelMapper
from src.compliance_checker import evaluate_session
from src.dataset_converter import dataset_to_session
from src.file_ingestion import ingest_file
from src.session_analysis import compute_session_metrics

FILES = [
    r"C:\Users\conno\OneDrive - Gannon University\Spring 2026\Senior Design\RigolDS0.csv",
    r"C:\Users\conno\OneDrive - Gannon University\Spring 2026\Senior Design\RigolDS1.csv",
    r"C:\Users\conno\OneDrive - Gannon University\Spring 2026\Senior Design\InverterPower_Simulation.xlsx",
    r"C:\Users\conno\OneDrive - Gannon University\Spring 2026\Senior Design\VSGFrequency_Simulation.xlsx",
]

OUT = Path("artifacts/data_audit/final_run_file_audit.md")


def sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            chunk = f.read(1024 * 1024)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def stats(arr: np.ndarray) -> dict[str, float]:
    valid = np.asarray(arr, dtype=np.float64)
    valid = valid[np.isfinite(valid)]
    if valid.size == 0:
        return {"min": float("nan"), "max": float("nan"), "mean": float("nan"), "rms": float("nan")}
    return {
        "min": float(np.min(valid)),
        "max": float(np.max(valid)),
        "mean": float(np.mean(valid)),
        "rms": float(np.sqrt(np.mean(valid ** 2))),
    }


def sample_interval(dataset) -> float | None:
    if dataset.time.size < 2:
        return None
    diffs = np.diff(dataset.time)
    diffs = diffs[diffs > 0]
    if diffs.size == 0:
        return None
    return float(np.median(diffs))


def derive_possible(mapped_channels: set[str]) -> list[str]:
    out: list[str] = []
    if {"v_an", "v_bn"}.issubset(mapped_channels):
        out.append("v_ab")
    if {"v_bn", "v_cn"}.issubset(mapped_channels):
        out.append("v_bc")
    if {"v_cn", "v_an"}.issubset(mapped_channels):
        out.append("v_ca")
    return out


def compliance_applicability(summary: dict) -> dict[str, str]:
    checks = {
        "voltage_regulation": "N/A",
        "thd": "N/A",
        "phase_imbalance": "N/A",
        "frequency": "N/A",
        "overcurrent": "N/A",
        "ride_through": "N/A",
        "fault_ride_through": "N/A",
    }
    phase = summary["phase_voltage"]
    has_phase = all(phase[ch].get("available") for ch in ("v_an", "v_bn", "v_cn"))
    has_freq = bool(summary["frequency"].get("available"))
    has_current = bool(summary["current_thresholds"].get("available"))

    if has_phase:
        checks["voltage_regulation"] = "Applicable"
        checks["thd"] = "Applicable"
        checks["phase_imbalance"] = "Applicable"
        checks["ride_through"] = "Applicable (or N/A if no sag observed)"
    if has_freq:
        checks["frequency"] = "Applicable"
    if has_current:
        checks["overcurrent"] = "Applicable"

    checks["fault_ride_through"] = "Applicable only with fault/status channel and active fault window"
    return checks


def main() -> None:
    mapper = ChannelMapper()
    OUT.parent.mkdir(parents=True, exist_ok=True)

    sections: list[str] = []
    sections.append("# Final Run File Audit\n")
    sections.append("Generated by scripts/final_run_file_audit.py\n")

    datasets = {}
    hashes = {}

    for file_path in FILES:
        ds = ingest_file(file_path)
        datasets[file_path] = ds
        hashes[file_path] = sha256(file_path)

    # Duplicate check for the two simulation files
    inv_path = FILES[2]
    vsg_path = FILES[3]
    inv = datasets[inv_path]
    vsg = datasets[vsg_path]
    inv_cols = list(inv.channels.keys())
    vsg_cols = list(vsg.channels.keys())
    sim_identical = False
    if inv.time.size == vsg.time.size and inv_cols == vsg_cols:
        sim_identical = np.allclose(inv.time, vsg.time, equal_nan=True)
        if sim_identical:
            for c in inv_cols:
                if not np.allclose(inv.channels[c], vsg.channels[c], equal_nan=True):
                    sim_identical = False
                    break

    sections.append("## Cross-file Findings\n")
    sections.append(f"- InverterPower SHA256: `{hashes[inv_path]}`")
    sections.append(f"- VSGFrequency SHA256: `{hashes[vsg_path]}`")
    sections.append(f"- InverterPower vs VSGFrequency identical data: **{sim_identical}**")
    if sim_identical:
        sections.append("- Conclusion: VSGFrequency_Simulation.xlsx is a duplicate power export, not a frequency dataset. This is a Simulink export issue (missing frequency variable).")
    sections.append("")

    for file_path in FILES:
        ds = datasets[file_path]
        suggested = mapper.auto_suggest(ds.raw_headers)
        mapped = {k: v for k, v in suggested.items() if v and v != "__unmapped__"}
        mapped_targets = set(mapped.values())

        # Build mapped dataset + capsule for metrics/compliance readiness
        mapped_ds = mapper.apply(ds, mapped)
        capsule = dataset_to_session(mapped_ds)
        capsule["_dataset"] = mapped_ds
        summary = compute_session_metrics(capsule)
        compliance_results = evaluate_session(capsule, profile="ieee_2800_inspired")

        sr = float(ds.sample_rate)
        dt = sample_interval(ds)
        num_cols = list(ds.channels.keys())

        sections.append(f"## {Path(file_path).name}\n")
        sections.append(f"- File path: `{file_path}`")
        sections.append(f"- File type: `{Path(file_path).suffix.lower()}` ({ds.source_type})")
        sections.append(f"- SHA256: `{hashes[file_path]}`")
        sections.append(f"- Columns: {', '.join(ds.raw_headers)}")
        sections.append(f"- Row count: {ds.row_count:,}")
        sections.append(f"- Detected time column: `{ds.meta.get('time_column')}`")
        sections.append(f"- Sample interval: `{dt if dt is not None else 'N/A'}` s")
        sections.append(f"- Sample rate: `{sr}` Hz")
        sections.append(f"- Duration: `{ds.duration}` s")
        sections.append(f"- Numeric columns: {', '.join(num_cols)}")
        sections.append(f"- Suggested canonical mapping: `{json.dumps(mapped, sort_keys=True)}`")

        sections.append("- Numeric stats:")
        for col in num_cols:
            st = stats(ds.channels[col])
            sections.append(
                f"  - {col}: min={st['min']:.6g}, max={st['max']:.6g}, mean={st['mean']:.6g}, rms={st['rms']:.6g}"
            )

        vsm_mode = summary["session"]["analysis_mode"] == "vsm"
        generic_mode = bool(num_cols)
        derived = derive_possible(mapped_targets)

        sections.append(f"- Supports VSM/GFM mode: `{vsm_mode}`")
        sections.append(f"- Supports generic analysis mode: `{generic_mode}`")
        sections.append(f"- Missing expected VSM channels: {', '.join(summary['session']['missing_expected_channels']) or 'none'}")
        sections.append(f"- Derived channels possible: {', '.join(derived) if derived else 'none'}")

        applicability = compliance_applicability(summary)
        sections.append("- Compliance checks applicability:")
        for k, v in applicability.items():
            sections.append(f"  - {k}: {v}")

        na_count = sum(1 for r in compliance_results if r.get("status") == "N/A")
        app_count = sum(1 for r in compliance_results if r.get("status") in {"PASS", "FAIL"})
        pass_count = sum(1 for r in compliance_results if r.get("status") == "PASS")
        sections.append(
            f"- Compliance run summary (ieee_2800_inspired): applicable={app_count}, pass={pass_count}, N/A={na_count}"
        )

        if Path(file_path).name == "RigolDS0.csv":
            sections.append("- Expected mapping check: CH1(V)->v_an, CH2(V)->v_bn, CH3(V)->v_cn")
            sections.append("- Expected derived channels check: v_ab, v_bc, v_ca")
        if Path(file_path).name == "RigolDS1.csv":
            sections.append("- CH4 note: channel treated honestly as raw numeric channel unless mapped/scaled as current sensor by user profile.")
        if Path(file_path).name == "InverterPower_Simulation.xlsx":
            sections.append("- Pinv canonical mapping: should map to p_mech for power analysis and event detection.")
        if Path(file_path).name == "VSGFrequency_Simulation.xlsx":
            if sim_identical:
                sections.append("- Result: duplicate of InverterPower_Simulation.xlsx (time + Pinv). No usable frequency variable exists in this file.")
                sections.append("- Re-export guidance: include one of freq, frequency, f_vsg, vsg_freq, omega, omega_r from Simulink.")

        if ds.warnings:
            sections.append("- Ingestion warnings:")
            for w in ds.warnings:
                sections.append(f"  - {w}")
        sections.append("")

    OUT.write_text("\n".join(sections) + "\n", encoding="utf-8")
    print(f"Wrote audit: {OUT}")


if __name__ == "__main__":
    main()
